export interface Address {
  id?: string | null,
  key?: string | null,
  firstName?: string | null,
  lastName?: string | null,
  line1?: string | null,
  line2?: string | null,
  phone?: string | null,
  email?: string | null,
  regionName?: string | null,
  countryCode?: string | null,
  countryName?: string | null,
  postalCode?: string | null,
  city?: string | null,
}
