export const COMPANY_DYNAMIC_PROPERTIES = {
  shortTextUsual: 'Short text | Usual',
  longTextUsual: 'Long text | Usual',
  integerUsual: 'Integer | Usual',
  decimalNumberUsual: 'Decimal number | Usual',
  date: 'Date',
  boolean: 'Boolean',
  image: 'Image',
  htmlUsual: 'HTML | Usual',
  shortTextMultilingual: 'Short text | Multilingual',
  longTextMultilingual: 'Long text | Multilingual',
  htmlMultilingual: 'HTML | Multilingual',
  shortTextMultivalue: 'Short text | Multivalue',
  decimalNumberMultivalue: 'Decimal number | Multivalue',
  integerMultivalue: 'Integer | Multivalue',
  shortTextDictionary: 'Dictionary',
  shortTextDictionaryMultilingual: 'Short text | Dictionary + Multilingual',
  shortTextDictionaryMultivalue: 'Short text | Dictionary + Multivalue',
  shortTextMultivalueDictionaryMultilingual: 'Short text | Multivalue + Dictionary + Multilingual',
  shortTextMultivalueMultilingual: 'Short text | Multivalue + Multilingual',
};
